edit profile
Crystalsage/CSI-DMCE pull request #4
Opened 2022-12-17 14:16 UTC by ZaurezTimmapuri

edit profile activity has been completed

2022-12-27 07:11 UTC, Crystalsage requested changes
I've left some suggestions. Can you fix them? LGTM otherwise. Thanks for working on this! :)

2022-12-27 07:11 UTC, Crystalsage commented on application/app/src/main/java/com/example/csi_dmce/Profile.kt
> +        val profile_button = findViewById<Button>(R.id.botton_profile)
There's a typo in `botton_profile`.

2022-12-27 07:11 UTC, Crystalsage commented on application/app/src/main/java/com/example/csi_dmce/Profile.kt
Can we remove these empty newlines?

2022-12-27 07:11 UTC, Crystalsage commented on application/app/src/main/java/com/example/csi_dmce/Profile.kt
Empty newlines.

2022-12-27 07:11 UTC, Crystalsage commented on application/app/src/main/java/com/example/csi_dmce/Profile.kt
> +
Empty newlines.

2022-12-31 12:54 UTC, ZaurezTimmapuri commented
changes have been made and has been updated

2023-01-02 15:59 UTC, Crystalsage approved these changes
Thanks for your work. LGTM.

2023-01-04 13:06 UTC, merged